title: Alexandre Robidel # your name (or website title) here
favicon: "/images/siteIcon3.png?raw=true"
logo: "/images/photo4.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b>Ingénieur logistique</b>
  <br>
  Leader Supply Chain chez Aptar
  <br><br>
  <a href="https://1drv.ms/b/s!Ag6bs6KyuioLkGbmzORSHDKkjO7p?e=XE02F8">Voir mon CV</a> 
  <br>
  <a href="https://www.linkedin.com/in/alexandre-robidel-meriller-5a8918178/">Voir mon profil LinkedIn</a> 
  <br><br>
  Mél : <br><a href="mailto:alexandre.robidel.meriller@gmail.com">alexandre.robidel.meriller@gmail.com</a> 
  <br><br>
  Tél : <br><a href="tel:0644953915">06 44 95 39 15</a> 
  
theme: jekyll-theme-minimal
google_analytics: "G-G9WE0Y8JDD" # your Google Analytics tracking ID here
