title: Alexandre Robidel # your name (or website title) here
logo: "/images/photo2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Ingénieur logistique 
  <br><br>
  Leader Supply Chain chez Aptar
  <br><br>
  <a href="https://www.linkedin.com/in/alexandre-robidel-meriller-5a8918178/">Voir mon profil LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-G9WE0Y8JDD # your Google Analytics tracking ID here
